# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.9/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.9/dist-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anthonygoddard962/fabrik

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anthonygoddard962/fabrik

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/lib/python3.9/dist-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.9/dist-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anthonygoddard962/fabrik/CMakeFiles /home/anthonygoddard962/fabrik//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anthonygoddard962/fabrik/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fabrik_lib

# Build rule for target.
fabrik_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fabrik_lib
.PHONY : fabrik_lib

# fast build rule for target.
fabrik_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/build
.PHONY : fabrik_lib/fast

#=============================================================================
# Target rules for targets named fabrik_run

# Build rule for target.
fabrik_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fabrik_run
.PHONY : fabrik_run

# fast build rule for target.
fabrik_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_run.dir/build.make CMakeFiles/fabrik_run.dir/build
.PHONY : fabrik_run/fast

GLnixAPP.o: GLnixAPP.cpp.o
.PHONY : GLnixAPP.o

# target to build an object file
GLnixAPP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GLnixAPP.cpp.o
.PHONY : GLnixAPP.cpp.o

GLnixAPP.i: GLnixAPP.cpp.i
.PHONY : GLnixAPP.i

# target to preprocess a source file
GLnixAPP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GLnixAPP.cpp.i
.PHONY : GLnixAPP.cpp.i

GLnixAPP.s: GLnixAPP.cpp.s
.PHONY : GLnixAPP.s

# target to generate assembly for a file
GLnixAPP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GLnixAPP.cpp.s
.PHONY : GLnixAPP.cpp.s

GLnixDEMO2.o: GLnixDEMO2.cpp.o
.PHONY : GLnixDEMO2.o

# target to build an object file
GLnixDEMO2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GLnixDEMO2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_run.dir/build.make CMakeFiles/fabrik_run.dir/GLnixDEMO2.cpp.o
.PHONY : GLnixDEMO2.cpp.o

GLnixDEMO2.i: GLnixDEMO2.cpp.i
.PHONY : GLnixDEMO2.i

# target to preprocess a source file
GLnixDEMO2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GLnixDEMO2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_run.dir/build.make CMakeFiles/fabrik_run.dir/GLnixDEMO2.cpp.i
.PHONY : GLnixDEMO2.cpp.i

GLnixDEMO2.s: GLnixDEMO2.cpp.s
.PHONY : GLnixDEMO2.s

# target to generate assembly for a file
GLnixDEMO2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GLnixDEMO2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_run.dir/build.make CMakeFiles/fabrik_run.dir/GLnixDEMO2.cpp.s
.PHONY : GLnixDEMO2.cpp.s

GeometryGen.o: GeometryGen.cpp.o
.PHONY : GeometryGen.o

# target to build an object file
GeometryGen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GeometryGen.cpp.o
.PHONY : GeometryGen.cpp.o

GeometryGen.i: GeometryGen.cpp.i
.PHONY : GeometryGen.i

# target to preprocess a source file
GeometryGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GeometryGen.cpp.i
.PHONY : GeometryGen.cpp.i

GeometryGen.s: GeometryGen.cpp.s
.PHONY : GeometryGen.s

# target to generate assembly for a file
GeometryGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/GeometryGen.cpp.s
.PHONY : GeometryGen.cpp.s

MathHelper.o: MathHelper.cpp.o
.PHONY : MathHelper.o

# target to build an object file
MathHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/MathHelper.cpp.o
.PHONY : MathHelper.cpp.o

MathHelper.i: MathHelper.cpp.i
.PHONY : MathHelper.i

# target to preprocess a source file
MathHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/MathHelper.cpp.i
.PHONY : MathHelper.cpp.i

MathHelper.s: MathHelper.cpp.s
.PHONY : MathHelper.s

# target to generate assembly for a file
MathHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/MathHelper.cpp.s
.PHONY : MathHelper.cpp.s

Timer.o: Timer.cpp.o
.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i
.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s
.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

antmath.o: antmath.cpp.o
.PHONY : antmath.o

# target to build an object file
antmath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/antmath.cpp.o
.PHONY : antmath.cpp.o

antmath.i: antmath.cpp.i
.PHONY : antmath.i

# target to preprocess a source file
antmath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/antmath.cpp.i
.PHONY : antmath.cpp.i

antmath.s: antmath.cpp.s
.PHONY : antmath.s

# target to generate assembly for a file
antmath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/antmath.cpp.s
.PHONY : antmath.cpp.s

cloth.o: cloth.cpp.o
.PHONY : cloth.o

# target to build an object file
cloth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/cloth.cpp.o
.PHONY : cloth.cpp.o

cloth.i: cloth.cpp.i
.PHONY : cloth.i

# target to preprocess a source file
cloth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/cloth.cpp.i
.PHONY : cloth.cpp.i

cloth.s: cloth.cpp.s
.PHONY : cloth.s

# target to generate assembly for a file
cloth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fabrik_lib.dir/build.make CMakeFiles/fabrik_lib.dir/cloth.cpp.s
.PHONY : cloth.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fabrik_lib"
	@echo "... fabrik_run"
	@echo "... GLnixAPP.o"
	@echo "... GLnixAPP.i"
	@echo "... GLnixAPP.s"
	@echo "... GLnixDEMO2.o"
	@echo "... GLnixDEMO2.i"
	@echo "... GLnixDEMO2.s"
	@echo "... GeometryGen.o"
	@echo "... GeometryGen.i"
	@echo "... GeometryGen.s"
	@echo "... MathHelper.o"
	@echo "... MathHelper.i"
	@echo "... MathHelper.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... antmath.o"
	@echo "... antmath.i"
	@echo "... antmath.s"
	@echo "... cloth.o"
	@echo "... cloth.i"
	@echo "... cloth.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

